-- Seed data generated from estructura.json — do not edit by hand.

INSERT INTO public.pages (slug, nombre, ruta) VALUES
  ('inicio', 'Inicio', '/'),
  ('nosotros', 'Nosotros', '/nosotros'),
  ('servicios', 'Servicios', '/servicios'),
  ('sensibilizacion', 'Sensibilización', '/sensibilizacion'),
  ('eventos', 'Eventos', '/eventos');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'inicio'), 'hero', '{"imagen_fondo":"Se sube desde el admin pero por ahora es fondo-hero.png","titulo":"Nuestro futuro no es desechable, *actuemos* ahora.","descripcion":"Recuperamos, transportamos y aprovechamos residuos sólidos en Suba, Engativá y Usaquén — devolviéndoles valor.","cta_texto":"Solicitar servicio","cta_url":"/solicitar"}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'inicio'), 'metricas', '{"dato_breve":"Impacto 2019 · 2026","titulo_principal":"Números que nutren la ciudad.","descripcion":"Cada tonelada aprovechada es un ciclo cerrado, un empleo digno para nuestros recuperadores ambientales y menos residuos enviados al relleno Doña Juana."}'::jsonb, 0);
INSERT INTO public.inicio_metricas (page_section_id, sort_order, titulo, numero, descripcion_tipo, descripcion_texto, descripcion_items) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'inicio') AND section_key = 'metricas'), 0, 'Toneladas aprovechadas', '699.564', 'texto', 'Acumulado 2019 – 2026 en las tres localidades atendidas.', '{}'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'inicio') AND section_key = 'metricas'), 1, 'Localidades', '3', 'texto', 'Suba · Engativá · Usaquén', '{}'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'inicio') AND section_key = 'metricas'), 2, 'ECAs ACTIVAS', '5', 'texto', 'Estaciones de clasificación.', '{}'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'inicio') AND section_key = 'metricas'), 3, 'ECAs:', '', 'items', '', ARRAY['Rincón', 'Prieto Hermanos', 'Ecoambit', 'JM Reciclaje', 'JM Reciclaje 2']::text[]);

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'inicio'), 'servicios_vista_general', '{"media_url":"","titulo_media":"Un día con quienes recuperan la ciudad","servicios_titulo":"Un ciclo completo, operado por nosotros."}'::jsonb, 0);
INSERT INTO public.inicio_servicios_cards (page_section_id, sort_order, numero, titulo) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'inicio') AND section_key = 'servicios_vista_general'), 0, '01', 'Recuperación y recolección selectiva'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'inicio') AND section_key = 'servicios_vista_general'), 1, '02', 'Transporte selectivo'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'inicio') AND section_key = 'servicios_vista_general'), 2, '03', 'Clasificación y almacenamiento'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'inicio') AND section_key = 'servicios_vista_general'), 3, '04', 'Pesaje y trazabilidad al SUI'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'inicio') AND section_key = 'servicios_vista_general'), 4, '05', 'Compactación de material');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'inicio'), 'frase', '{"titulo_pequeno":"Nuestra convicción","texto":"Aprovechar no es solo recoger. Es reconocer el valor de lo que la ciudad estaba a punto de olvidar."}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'nosotros'), 'hero', '{"imagen_fondo":"Se puede subir","titulo":"Somos quienes recuperan la ciudad","descripcion":"ASOFRAIN E.S.P. — una organización de recuperadores ambientales que presta el servicio público de aprovechamiento en Bogotá desde 2006.","cta_1_texto":"Conocer la historia","cta_1_url":"","cta_2_texto":"Ver aliados","cta_2_url":""}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'nosotros'), 'quienes_somos', '{"titulo":"Una empresa pública, operada por sus recuperadores.","descripcion":"ASOFRAIN E.S.P. es una Empresa de Servicios Públicos constituida por recuperadores ambientales, reconocida ante la Superintendencia de Servicios Públicos Domiciliarios (SSPD) como prestadora del servicio público de aprovechamiento en Bogotá D.C. Operamos bajo el marco tarifario CRA 720 de 2015 y el Decreto 596 de 2016, con enfoque territorial en las localidades de Suba, Engativá y Usaquén. Nuestra razón de ser combina un servicio esencial para la ciudad con la dignificación laboral de las familias recuperadoras que integran la organización."}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'nosotros'), 'historia', '{"titulo":"Desde 2006, tejiendo un ciclo de valor."}'::jsonb, 0);
INSERT INTO public.nosotros_historia_filas (page_section_id, sort_order, ano, titulo, descripcion) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'historia'), 0, '2006', 'Origen en Suba', 'Un grupo de recuperadores ambientales de Suba se organiza informalmente para dignificar su labor y avanzar hacia la formalización.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'historia'), 1, '2013', 'Auto 275 y formalización', 'Se avanza en el proceso de formalización tras los autos de la Corte Constitucional que reconocen a los recuperadores como sujetos de especial protección.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'historia'), 2, '2019', 'Nace ASOFRAIN E.S.P.', 'Denominación actual como Empresa de Servicios Públicos. Registro ante la SSPD y la UAESP. Se abre operación en Engativá y Usaquén.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'historia'), 3, 'Hoy', '699.564 toneladas aprovechadas', '5 estaciones de clasificación (ECAs), servicio consolidado en tres localidades y un programa creciente de sensibilización territorial.');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'nosotros'), 'mision', '{"descripcion":"Prestar el servicio público de aprovechamiento en Bogotá con excelencia técnica, dignificando a nuestros recuperadores ambientales y devolviendo valor a la ciudad y al medio ambiente."}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'nosotros'), 'vision', '{"descripcion":"Ser referente nacional en aprovechamiento de residuos, con cobertura ampliada, tecnología de trazabilidad y un modelo replicable que consolide a Bogotá como una ciudad de economía circular."}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'nosotros'), 'valores', '{"titulo":"Ocho principios no negociables."}'::jsonb, 0);
INSERT INTO public.nosotros_valores_cuadros (page_section_id, sort_order, titulo, descripcion) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'valores'), 0, 'Compromiso ambiental', 'Cada decisión operativa considera el impacto ecológico.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'valores'), 1, 'Responsabilidad social', 'Con nuestros recuperadores, sus familias, con Bogotá.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'valores'), 2, 'Integridad', 'Trazabilidad y transparencia en cada tonelada aprovechada.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'valores'), 3, 'Respeto', 'Trato digno al recuperador, al usuario y al material.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'valores'), 4, 'Calidad', 'Procesos técnicos verificables y mejora continua.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'valores'), 5, 'Trabajo en equipo', 'Somos una asociación antes que una empresa.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'valores'), 6, 'Innovación', 'Compactación, trazabilidad digital y rutas optimizadas.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'valores'), 7, 'Servicio', 'Atención cercana al usuario y respuesta oportuna.');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'nosotros'), 'objeto_social', '{"titulo":"Aprovechar residuos, dignificar oficios.","descripcion":"La prestación del servicio público de aprovechamiento en el marco del Decreto 596 de 2016, garantizando condiciones laborales dignas para las familias recuperadoras que integran la organización."}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'nosotros'), 'objeto_ambiental', '{"titulo":"Extender la vida útil del relleno Doña Juana.","descripcion":"Reducir la cantidad de residuos aprovechables que terminan enterrados, promover la economía circular en la fuente y contribuir a las metas del PGIRS Bogotá."}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'nosotros'), 'frase_1', '{"titulo_pequeno":"COMPROMISO CON BOGOTÁ","texto":"Con cada usuario, un ciclo cerrado. Con la ciudad, un pacto de economía circular."}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'nosotros'), 'entidades_aliadas', '{"titulo":"Operamos de la mano del ecosistema institucional."}'::jsonb, 0);
INSERT INTO public.nosotros_entidades_aliados (page_section_id, sort_order, logo_url, titulo, descripcion) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'entidades_aliadas'), 0, 'Permite subir el logo', 'SSPD', 'Superintendencia de Servicios Públicos Domiciliarios'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'entidades_aliadas'), 1, 'Permite subir el logo', 'UAESP', 'Unidad Administrativa Especial de Servicios Públicos'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'entidades_aliadas'), 2, 'Permite subir el logo', 'ALCALDÍAS', 'Alcaldías Locales de Suba, Engativá y Usaquén'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'entidades_aliadas'), 3, 'Permite subir el logo', 'RECOLECCIÓN', 'Prestadores del servicio de recolección de residuos no aprovechables'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'entidades_aliadas'), 4, 'Permite subir el logo', 'CRA', 'Comisión de Regulación de Agua Potable y Saneamiento Básico'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'entidades_aliadas'), 5, 'Permite subir el logo', 'MINVIVIENDA', 'Ministerio de Vivienda, Ciudad y Territorio'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'nosotros') AND section_key = 'entidades_aliadas'), 6, 'Permite subir el logo', 'Secretaría Distrital de Ambiente', 'Trabajamos con la SDA en programas de sensibilización territorial y en la meta distrital de aprovechamiento.');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'servicios'), 'hero', '{"imagen_fondo":"Se puede subir la imagen","titulo":"El ciclo de principio a fin","descripcion":"Cinco procesos técnicos y un plus diferencial. Cada uno operado directamente por ASOFRAIN, con protocolos verificables y trazabilidad al SUI.","descripcion_2":"Suba · Engativá · Usaquén"}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'servicios'), 'servicios', '{"titulo":"Cinco procesos, un solo operador."}'::jsonb, 0);
INSERT INTO public.servicios_items (page_section_id, sort_order, titulo, descripcion) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicios'), 0, 'Recuperación de residuos aprovechables', 'Identificación, selección y recuperación en la fuente de materiales con potencial de aprovechamiento.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicios'), 1, 'Recolección selectiva', 'Rutas programadas puerta a puerta y por macrorruta, con horarios definidos por localidad.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicios'), 2, 'Transporte selectivo', 'Vehículos autorizados, cumpliendo la normatividad de transporte de residuos aprovechables.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicios'), 3, 'Clasificación y almacenamiento', 'En nuestras 5 ECAs — Rincón, Prieto Hermanos, Ecoambit, JM Reciclaje y JM Reciclaje 2 — con protocolos por tipo de material.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicios'), 4, 'Pesaje y trazabilidad', 'Reporte al SUI (Sistema Único de Información) con toneladas efectivamente aprovechadas por usuario y por localidad, según requerimientos de la SSPD.');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'servicios'), 'servicio_destacado_plus', '{"subtitulo_pequeno":"PLUS DIFERENCIAL","titulo":"Compactación de material aprovechable.","descripcion":"Optimizamos el volumen del material antes del transporte a la industria transformadora. Seis beneficios verificables."}'::jsonb, 0);
INSERT INTO public.servicios_destacado_items (page_section_id, sort_order, titulo, descripcion) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicio_destacado_plus'), 0, 'Reducción de volumen', 'Hasta 4× menos espacio en transporte y almacenamiento.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicio_destacado_plus'), 1, 'Menos viajes, menos emisiones', 'Rutas optimizadas y menor huella de carbono.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicio_destacado_plus'), 2, 'Mayor eficiencia operativa', 'Más toneladas gestionadas por jornada.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicio_destacado_plus'), 3, 'Mejor precio de venta', 'Presentación estandarizada para la industria.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicio_destacado_plus'), 4, 'Menos contaminación cruzada', 'Separación firme entre corrientes de material.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'servicio_destacado_plus'), 5, 'Bienestar para el equipo', 'Menos esfuerzo físico en manipulación.');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'servicios'), 'rutas_localidades_horarios', '{"titulo":"Dónde estamos, cuándo llegamos.","descripcion":"Sujeto a programación operativa. Coordinamos directamente con cada usuario para confirmar día y hora exactos."}'::jsonb, 0);
INSERT INTO public.servicios_rutas_filas (page_section_id, sort_order, localidad, dias, horario, activo) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'rutas_localidades_horarios'), 0, 'Suba', 'Lunes a sábado', '7:00 am – 5:00 pm', true),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'rutas_localidades_horarios'), 1, 'Engativá', 'Lunes a sábado', '7:00 am – 5:00 pm', true),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'rutas_localidades_horarios'), 2, 'Usaquén', 'Lunes a sábado', '7:00 am – 5:00 pm', true);

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'servicios'), 'sectores_atendidos', '{"titulo":"Nueve sectores, una misma ciudad."}'::jsonb, 0);
INSERT INTO public.servicios_sectores (page_section_id, sort_order, imagen_url, titulo, descripcion) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'sectores_atendidos'), 0, 'Se puede subir la imagen', 'Propiedad horizontal', 'Conjuntos residenciales y oficinas'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'sectores_atendidos'), 1, 'Se puede subir la imagen', 'Entidades públicas', 'Distritales y nacionales'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'sectores_atendidos'), 2, 'Se puede subir la imagen', 'Empresas e industria', 'Manufactura y servicios'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'sectores_atendidos'), 3, 'Se puede subir la imagen', 'Instituciones educativas', 'Colegios y universidades'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'sectores_atendidos'), 4, 'Se puede subir la imagen', 'Comercio', 'Locales, plazas y centros'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'sectores_atendidos'), 5, 'Se puede subir la imagen', 'Sector salud', 'Solo residuos ordinarios aprovechables'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'sectores_atendidos'), 6, 'Se puede subir la imagen', 'Hotelero y gastronómico', 'Hoteles, restaurantes, food halls'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'sectores_atendidos'), 7, 'Se puede subir la imagen', 'Oficinas y empresarial', 'Coworkings, sedes corporativas'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'sectores_atendidos'), 8, 'Se puede subir la imagen', 'Comunidades y ciudadanía', 'Usuarios en general');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'servicios'), 'tarifas_y_productos', '{"titulo":"Un marco tarifario público y regulado.","descripcion":"El servicio público de aprovechamiento está regulado por la Comisión de Regulación de Agua Potable y Saneamiento Básico (CRA) mediante la Resolución 720 de 2015. El valor se calcula por tonelada efectivamente aprovechada y se acredita a la factura del servicio de aseo. El usuario no paga extra por reciclar — al contrario, incentiva su tarifa.","cta_texto":"Ver normatividad completa →","cta_url":""}'::jsonb, 0);
INSERT INTO public.servicios_productos (page_section_id, sort_order, nombre) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'tarifas_y_productos'), 0, 'Papel y cartón'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'tarifas_y_productos'), 1, 'Vidrio'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'tarifas_y_productos'), 2, 'Metales no ferrosos'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'tarifas_y_productos'), 3, 'RAEE (electrónicos)'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'tarifas_y_productos'), 4, 'Plásticos (PET, PP, PEBD)'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'tarifas_y_productos'), 5, 'Metales ferrosos'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'tarifas_y_productos'), 6, 'Tetrapak'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'servicios') AND section_key = 'tarifas_y_productos'), 7, 'Textiles');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'servicios'), 'cta_final', '{"titulo":"¿Listo para agendar tu servicio?","descripcion":"Un asesor confirmará ruta, día y volumen estimado en menos de 24 horas hábiles.","boton_texto":"Solicitar servicio →","boton_url":""}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'sensibilizacion'), 'encabezado', '{"titulo":"Tres poblaciones, una misma raíz.","descripcion":"Reciclar es un hábito colectivo. Diseñamos programas específicos para cada audiencia."}'::jsonb, 0);
INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'sensibilizacion'), 'tipos_sensibilizacion', '{}'::jsonb, 0);
INSERT INTO public.sensibilizacion_tipos (page_section_id, sort_order, imagen_url, tipo, titulo) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion'), 0, 'Se carga desde admin', '01 · NIÑOS', 'Semillas que separan.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion'), 1, 'Se carga desde admin', '02 · PROPIEDAD HORIZONTAL', 'Conjuntos que aprovechan.'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion'), 2, 'Se carga desde admin', '03 · USUARIOS EN GENERAL', 'Barrios que se reconocen.');

INSERT INTO public.sensibilizacion_vinetas (tipo_id, sort_order, texto) VALUES
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 0), 0, 'Reciclatones escolares'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 0), 1, 'Talleres ambientales'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 0), 2, 'Juegos y dinámicas educativas'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 0), 3, 'Cuentos ecológicos'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 0), 4, 'Concursos de reciclaje');

INSERT INTO public.sensibilizacion_vinetas (tipo_id, sort_order, texto) VALUES
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 1), 0, 'Capacitaciones a administraciones y consejos'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 1), 1, 'Señalización de puntos ecológicos'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 1), 2, 'Jornadas de sensibilización'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 1), 3, 'Reciclatones comunitarias'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 1), 4, 'Asesoría técnica en separación en la fuente');

INSERT INTO public.sensibilizacion_vinetas (tipo_id, sort_order, texto) VALUES
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 2), 0, 'Charlas comunitarias'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 2), 1, 'Campañas de sensibilización ambiental'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 2), 2, 'Jornadas de reciclaje'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 2), 3, 'Asesoría en separación en la fuente'),
  ((SELECT id FROM public.sensibilizacion_tipos WHERE page_section_id = (SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'tipos_sensibilizacion') AND sort_order = 2), 4, 'Acompañamiento territorial');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'sensibilizacion'), 'galeria', '{"titulo":""}'::jsonb, 0);
INSERT INTO public.sensibilizacion_galeria (page_section_id, sort_order, url, alt) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'galeria'), 0, 'Se sube desde admin', ''),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'galeria'), 1, 'Se sube desde admin', ''),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'galeria'), 2, 'Se sube desde admin', ''),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'galeria'), 3, 'Se sube desde admin', ''),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'galeria'), 4, 'Se sube desde admin', ''),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'galeria'), 5, 'Se sube desde admin', ''),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'sensibilizacion') AND section_key = 'galeria'), 6, 'Se sube desde admin', '');

INSERT INTO public.page_sections (page_id, section_key, data, sort_order) VALUES ((SELECT id FROM public.pages WHERE slug = 'eventos'), 'listado_eventos', '{"titulo":"La familia ASOFRAIN, celebrada.","filtro_por_ano_activo":true,"filtro_por_ano_valor_default":"Año actual"}'::jsonb, 0);
INSERT INTO public.eventos_cards (page_section_id, sort_order, foto_url, foto_alt, fecha, titulo) VALUES
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'eventos') AND section_key = 'listado_eventos'), 0, 'Se sube desde admin', '', '08 MAR', 'Día Internacional de la Mujer'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'eventos') AND section_key = 'listado_eventos'), 1, 'Se sube desde admin', '', '19 MAR', 'Día del Hombre'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'eventos') AND section_key = 'listado_eventos'), 2, 'Se sube desde admin', '', 'MAYO', 'Día de la Madre'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'eventos') AND section_key = 'listado_eventos'), 3, 'Se sube desde admin', '', 'JUNIO', 'Día del Padre'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'eventos') AND section_key = 'listado_eventos'), 4, 'Se sube desde admin', '', 'ABRIL', 'Día del Niño'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'eventos') AND section_key = 'listado_eventos'), 5, 'Se sube desde admin', '', '31 OCT', 'Halloween'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'eventos') AND section_key = 'listado_eventos'), 6, 'Se sube desde admin', '', 'DICIEMBRE', 'Navidad'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'eventos') AND section_key = 'listado_eventos'), 7, 'Se sube desde admin', '', 'INSTITUCIONAL', 'Aniversarios y actividades'),
  ((SELECT id FROM public.page_sections WHERE page_id = (SELECT id FROM public.pages WHERE slug = 'eventos') AND section_key = 'listado_eventos'), 8, 'Se sube desde admin', '', 'BIENESTAR', 'Jornadas de integración');

